name: play_android
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  
  # iOS风格图标
  cupertino_icons: ^0.1.2
  # 吐司
  fluttertoast: ^3.1.0
  # 轮播图
  flutter_swiper: ^1.1.6
  # webView插件,不支持iOS的侧滑
  flutter_webview_plugin: ^0.3.11
  # 上面那个性能不好 换这个 这个使用原生的WebKit,而且支持侧滑
  webview_flutter: ^0.3.19+9
  # 下拉刷新与上拉加载
  pull_to_refresh: ^1.5.8
  # cell的侧滑删除,还有其他可以使用的地方
  flutter_slidable: "^0.5.4"
  # html化
  flutter_html: ^0.11.1
  # 图片选择 选择图片
  image_picker:
  # 跑马灯
  marquee_flutter:
  # 图片缓存
  cached_network_image: 
  # FlutterUIKit
  flukit: 

  #屏幕适配,没有使用
  flutter_screenutil: ^0.5.3

  #设备信息
  device_info:

  #iOS中的UserDefine
  shared_preferences: ^0.5.3+4 #SharedPreferences

  #文件读写
  path_provider:

  #Android中的EventBus
  event_bus: ^1.1.1

  #网络请求库
  dio: ^3.0.9

  #跳转 拨打电话和浏览器
  url_launcher:

  #json序列化与反序列化
  json_annotation: ^2.0.0

  #flutter调用微信SDK,虽然我估计不会集成微信分享功能
  #fluwx: ^2.0.8+1

  #BLoC框架
  flutter_bloc:

  # 图片保存框架
  image_gallery_saver:

  # 升级框架
  r_upgrade:

dev_dependencies:
  flutter_test:
    sdk: flutter

  #json解析脚本,不一定会用到
  json_model: #latest version
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/ic_head.jpeg
    - assets/images/ic_eye.png
    - assets/images/placeholder.png
    - assets/images/saber.jpg
    - assets/images/season_ali_pay.jpg
    - assets/images/saber_logo.jpg
    - assets/images/welcome_1.png
    - assets/images/welcome_2.jpg
    - assets/images/launchImage.png
  
  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf

    - family: noto
      fonts:
        - asset: fonts/NotoSansCJKsc-Regular.otf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
