name: play_android
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^3.1.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^1.0.5
  pull_to_refresh: ^1.6.4
  flutter_slidable: ^0.5.7
  flutter_html: ^0.11.1
  image_picker: null
  marquee_flutter: null
  cached_network_image: null
  drag_container: ^1.0.1
  wrapper: ^1.0.1
  flutter_intro: null
  flutter_easyloading: ^2.0.0
  flutter_screenutil: ^0.5.3
  device_info: ^2.0.0
  lpinyin: ^2.0.1
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  event_bus: ^1.1.1
  dio: ^4.0.0
  url_launcher: ^6.0.3
  json_annotation: ^2.0.0
  flutter_bloc: null
  image_gallery_saver: null
  r_upgrade: null
  open_file: null
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/ic_head.jpeg
  - assets/images/ic_eye.png
  - assets/images/placeholder.png
  - assets/images/saber.jpg
  - assets/images/season_ali_pay.jpg
  - assets/images/saber_logo.jpg
  - assets/images/welcome_1.png
  - assets/images/welcome_2.jpg
  - assets/images/launchImage.png
  - assets/images/upgrade.png
  fonts:
  - family: iconfont
    fonts:
    - asset: fonts/iconfont.ttf
  - family: noto
    fonts:
    - asset: fonts/NotoSansCJKsc-Regular.otf
