name: play_android
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  pull_to_refresh: ^1.5.8
  flutter_slidable: "^0.5.4"
  flutter_html: ^0.11.1
  image_picker: ^0.6.4
  marquee_flutter: #跑马灯

  #屏幕适配
  flutter_screenutil: ^0.5.3

  #iOS中的UserDefine
  shared_preferences: ^0.5.3+4 #SharedPreferences

  #Android中的EventBus
  event_bus: ^1.1.1

  #网络请求库
  dio: ^2.1.0

  #json序列化与反序列化
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #json解析脚本,不一定会用到
  json_model: #latest version
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/welcome_bg.jpeg
    - assets/images/ic_head.jpeg
    - assets/images/ic_eye.png
    - assets/images/placeholder.png
    - assets/images/we_chart_mark.jpg
    - assets/images/alipay.jpg
    - assets/images/we_chart_pay.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
